# Minimal starship configuration
# Shows only directory + git:(branch) for git repositories
format = "$directory$git_branch $character"

[directory]
style = "cyan"

# show git branch with branch in purple
[git_branch]
format = "git:([$branch](bold red))"
